### PR TITLE
Added React component scaffold for bug sqasher 

### LINKED ISSUE #1: Add react project to bugs in the component
Add react project for beginners and find bugs in the component

### PR DESCRIPTION
**Pull request by Mrinalaot**
Added React component scaffold for bug sqasher 

As part of Hacktober fest @Mrinal-Ghosh-epam

### CODE REVIEW

File: react-components-for-beginners/src/App.js [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+        <p>
+          Edit <code>src/App.js</code> and save to reload.
+        </p>
+        <a
+          className="App-link"
+          href="https://reactjs.org"
+          target="_blank"
+          rel="noopener noreferrer"
+        >
+          Learn React
```
Comment (Mrinal-Ghosh-epam) [inline react-components-for-beginners/src/App.js:18]: Can you please create a folder for components?

Comment (Mrinalaot) [reply react-components-for-beginners/src/App.js:18]: Sure let me work on it
